# env should be created with mamba
name: flrec
channels:
  - conda-forge
dependencies:
  - python=3.9.7
  - pip
  # SCICOMP
  - numpy=1.21.4
  - scipy=1.7.2
  - pandas=1.3.4
  - numba=0.53.1
  - matplotlib
  - ipykernel
  - pyarrow 
  - jupyter
  - pip:
    - ipypb